version: '3.7'
services:
  site_app:
    build:
      context: .
      dockerfile: ./.docker/site/php/Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    command: /entrypoint.sh
    volumes:
      - ./site/:/var/www/html
      - ./.docker/site/php/entrypoint.sh:/entrypoint.sh
    networks:
      - meetancos_net

  site_nginx:
    image: nginx:1.19.0-alpine
    restart: unless-stopped
    tty: true
    ports:
      - "${SITE_HTTP_PORT}:80"
      - "${SITE_HTTPS_PORT}:443"
    volumes:
      - ./site/:/var/www/html
      - ./.docker/site/nginx/conf.d/:/etc/nginx/conf.d/
      - ./.docker/site/nginx/ssl/:/etc/nginx/ssl/
    networks:
      - meetancos_net


networks:
  meetancos_net:
    driver: bridge
